<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Comparing means in R | An R companion to Statistical Thinking for the 21st Century</title>
  <meta name="description" content="A book about doing statistics using R." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Comparing means in R | An R companion to Statistical Thinking for the 21st Century" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book about doing statistics using R." />
  <meta name="github-repo" content="statsthinking21/statsthinking21-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Comparing means in R | An R companion to Statistical Thinking for the 21st Century" />
  
  <meta name="twitter:description" content="A book about doing statistics using R." />
  

<meta name="author" content="Copyright 2020 Russell A. Poldrack" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-general-linear-model-in-r.html"/>
<link rel="next" href="practical-statistical-modeling-in-r.html"/>
<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129414074-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129414074-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>0.1</b> Why R?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#the-golden-age-of-data"><i class="fa fa-check"></i><b>0.2</b> The golden age of data</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#an-open-source-book"><i class="fa fa-check"></i><b>0.3</b> An open source book</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.4</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#why-programming-is-hard-to-learn"><i class="fa fa-check"></i><b>1.1</b> Why programming is hard to learn</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#use-the-web"><i class="fa fa-check"></i><b>1.1.1</b> Use the web</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#rubber-duck-debugging"><i class="fa fa-check"></i><b>1.1.2</b> Rubber duck debugging</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#using-rstudio"><i class="fa fa-check"></i><b>1.2</b> Using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-started-with-r"><i class="fa fa-check"></i><b>1.3</b> Getting started with R</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variables"><i class="fa fa-check"></i><b>1.4</b> Variables</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#functions"><i class="fa fa-check"></i><b>1.5</b> Functions</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectors"><i class="fa fa-check"></i><b>1.6</b> Vectors</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#math-with-vectors"><i class="fa fa-check"></i><b>1.7</b> Math with vectors</a></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-frames"><i class="fa fa-check"></i><b>1.8</b> Data Frames</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#using-r-libraries"><i class="fa fa-check"></i><b>1.9</b> Using R libraries</a></li>
<li class="chapter" data-level="1.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#working-with-data-files"><i class="fa fa-check"></i><b>1.10</b> Working with data files</a></li>
<li class="chapter" data-level="1.11" data-path="introduction-to-r.html"><a href="introduction-to-r.html#learning-objectives"><i class="fa fa-check"></i><b>1.11</b> Learning objectives</a></li>
<li class="chapter" data-level="1.12" data-path="introduction-to-r.html"><a href="introduction-to-r.html#suggested-readings-and-videos"><i class="fa fa-check"></i><b>1.12</b> Suggested readings and videos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html"><i class="fa fa-check"></i><b>2</b> Summarizing data using R (with Lucy King)</a><ul>
<li class="chapter" data-level="2.1" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#introduction-to-the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Introduction to the Tidyverse</a><ul>
<li class="chapter" data-level="2.1.1" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#making-a-data-frame-using-tibble"><i class="fa fa-check"></i><b>2.1.1</b> Making a data frame using tibble()</a></li>
<li class="chapter" data-level="2.1.2" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#selecting-an-element"><i class="fa fa-check"></i><b>2.1.2</b> Selecting an element</a></li>
<li class="chapter" data-level="2.1.3" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#adding-a-row-or-column"><i class="fa fa-check"></i><b>2.1.3</b> Adding a row or column</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#creating-or-modifying-variables-using-mutate"><i class="fa fa-check"></i><b>2.2</b> Creating or modifying variables using <code>mutate()</code></a><ul>
<li class="chapter" data-level="2.2.1" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#remove-a-column-using-the-select-function"><i class="fa fa-check"></i><b>2.2.1</b> Remove a column using the select() function</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#tidyverse-in-action"><i class="fa fa-check"></i><b>2.3</b> Tidyverse in action</a></li>
<li class="chapter" data-level="2.4" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#looking-at-individual-variables-using-pull-and-head"><i class="fa fa-check"></i><b>2.4</b> Looking at individual variables using pull() and head()</a></li>
<li class="chapter" data-level="2.5" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#computing-a-frequency-distribution-section-reffrequency-distributions"><i class="fa fa-check"></i><b>2.5</b> Computing a frequency distribution (Section @ref(frequency-distributions))</a></li>
<li class="chapter" data-level="2.6" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#computing-a-cumulative-distribution-section-refcumulative-distributions"><i class="fa fa-check"></i><b>2.6</b> Computing a cumulative distribution (Section @ref(cumulative-distributions))</a></li>
<li class="chapter" data-level="2.7" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#data-cleaning-and-tidying-with-r"><i class="fa fa-check"></i><b>2.7</b> Data cleaning and tidying with R</a><ul>
<li class="chapter" data-level="2.7.1" data-path="summarizing-data-using-r-with-lucy-king.html"><a href="summarizing-data-using-r-with-lucy-king.html#statistics-attitude-data-from-course-survey"><i class="fa fa-check"></i><b>2.7.1</b> Statistics attitude data from course survey</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html"><i class="fa fa-check"></i><b>3</b> Data visualization using R (with Anna Khazenzon)</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#the-grammar-of-graphics"><i class="fa fa-check"></i><b>3.1</b> The grammar of graphics</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#getting-started"><i class="fa fa-check"></i><b>3.2</b> Getting started</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#lets-think-through-a-visualization"><i class="fa fa-check"></i><b>3.3</b> Let’s think through a visualization</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#plotting-the-distribution-of-a-single-variable"><i class="fa fa-check"></i><b>3.4</b> Plotting the distribution of a single variable</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#histogram"><i class="fa fa-check"></i><b>3.4.1</b> Histogram</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#density-plot"><i class="fa fa-check"></i><b>3.4.2</b> Density plot</a></li>
<li class="chapter" data-level="3.4.3" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#bar-vs.line-plots"><i class="fa fa-check"></i><b>3.4.3</b> Bar vs. line plots</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#plots-with-two-variables"><i class="fa fa-check"></i><b>3.5</b> Plots with two variables</a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#adding-on-variables"><i class="fa fa-check"></i><b>3.5.1</b> Adding on variables</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#plotting-dispersion"><i class="fa fa-check"></i><b>3.5.2</b> Plotting dispersion</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#scatter-plot"><i class="fa fa-check"></i><b>3.5.3</b> Scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#creating-a-more-complex-plot"><i class="fa fa-check"></i><b>3.6</b> Creating a more complex plot</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualization-using-r-with-anna-khazenzon.html"><a href="data-visualization-using-r-with-anna-khazenzon.html#additional-reading-and-resources"><i class="fa fa-check"></i><b>3.7</b> Additional reading and resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html"><i class="fa fa-check"></i><b>4</b> Fitting simple models using R</a><ul>
<li class="chapter" data-level="4.1" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html#mean"><i class="fa fa-check"></i><b>4.1</b> Mean</a></li>
<li class="chapter" data-level="4.2" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html#median"><i class="fa fa-check"></i><b>4.2</b> Median</a></li>
<li class="chapter" data-level="4.3" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html#mode"><i class="fa fa-check"></i><b>4.3</b> Mode</a></li>
<li class="chapter" data-level="4.4" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html#variability"><i class="fa fa-check"></i><b>4.4</b> Variability</a></li>
<li class="chapter" data-level="4.5" data-path="fitting-simple-models-using-r.html"><a href="fitting-simple-models-using-r.html#z-scores"><i class="fa fa-check"></i><b>4.5</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html"><i class="fa fa-check"></i><b>5</b> Probability in R (with Lucy King)</a><ul>
<li class="chapter" data-level="5.1" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#basic-probability-calculations"><i class="fa fa-check"></i><b>5.1</b> Basic probability calculations</a></li>
<li class="chapter" data-level="5.2" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#empirical-frequency-section-refempirical-frequency"><i class="fa fa-check"></i><b>5.2</b> Empirical frequency (Section @ref(empirical-frequency))</a></li>
<li class="chapter" data-level="5.3" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#conditional-probability-section-refconditional-probability"><i class="fa fa-check"></i><b>5.3</b> Conditional probability (Section @ref(conditional-probability))</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-in-r.html"><a href="sampling-in-r.html"><i class="fa fa-check"></i><b>6</b> Sampling in R</a><ul>
<li class="chapter" data-level="6.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sampling-error-section-refsamplingerror"><i class="fa fa-check"></i><b>6.1</b> Sampling error (Section @ref(samplingerror))</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#central-limit-theorem"><i class="fa fa-check"></i><b>6.2</b> Central limit theorem</a></li>
<li class="chapter" data-level="6.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#confidence-intervals-section-refconfidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence intervals (Section @ref(confidence-intervals))</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html"><i class="fa fa-check"></i><b>7</b> Resampling and simulation in R</a><ul>
<li class="chapter" data-level="7.1" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#generating-random-samples-section-refgenerating-random-numbers"><i class="fa fa-check"></i><b>7.1</b> Generating random samples (Section @ref(generating-random-numbers))</a></li>
<li class="chapter" data-level="7.2" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#simulating-the-maximum-finishing-time"><i class="fa fa-check"></i><b>7.2</b> Simulating the maximum finishing time</a></li>
<li class="chapter" data-level="7.3" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#the-bootstrap"><i class="fa fa-check"></i><b>7.3</b> The bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html"><i class="fa fa-check"></i><b>8</b> Hypothesis testing in R</a><ul>
<li class="chapter" data-level="8.1" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#simple-example-coin-flipping-section-refrandomization-very-simple"><i class="fa fa-check"></i><b>8.1</b> Simple example: Coin-flipping (Section @ref(randomization-very-simple))</a></li>
<li class="chapter" data-level="8.2" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#simulating-p-values"><i class="fa fa-check"></i><b>8.2</b> Simulating p-values</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html"><i class="fa fa-check"></i><b>9</b> Statistical power in R</a><ul>
<li class="chapter" data-level="9.1" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#computing-confidence-intervals"><i class="fa fa-check"></i><b>9.1</b> Computing confidence intervals</a><ul>
<li class="chapter" data-level="9.1.1" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#theoretical"><i class="fa fa-check"></i><b>9.1.1</b> Theoretical</a></li>
<li class="chapter" data-level="9.1.2" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#bootstrap"><i class="fa fa-check"></i><b>9.1.2</b> Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#effect-size"><i class="fa fa-check"></i><b>9.2</b> Effect Size</a><ul>
<li class="chapter" data-level="9.2.1" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#cohens-d"><i class="fa fa-check"></i><b>9.2.1</b> Cohen’s d</a></li>
<li class="chapter" data-level="9.2.2" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#pearsons-r"><i class="fa fa-check"></i><b>9.2.2</b> Pearson’s r</a></li>
<li class="chapter" data-level="9.2.3" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#odds-ratio"><i class="fa fa-check"></i><b>9.2.3</b> Odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#power-analysis"><i class="fa fa-check"></i><b>9.3</b> Power analysis</a></li>
<li class="chapter" data-level="9.4" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#power-curves"><i class="fa fa-check"></i><b>9.4</b> Power curves</a></li>
<li class="chapter" data-level="9.5" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#simulating-statistical-power"><i class="fa fa-check"></i><b>9.5</b> Simulating statistical power</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html"><i class="fa fa-check"></i><b>10</b> Bayesian statistics in R</a><ul>
<li class="chapter" data-level="10.1" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#a-simple-example-section-refdoing-bayesian-estimation"><i class="fa fa-check"></i><b>10.1</b> A simple example (Section @ref(doing-bayesian-estimation))</a></li>
<li class="chapter" data-level="10.2" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#estimating-posterior-distributions-section-refestimating-posterior-distributions"><i class="fa fa-check"></i><b>10.2</b> Estimating posterior distributions (Section @ref(estimating-posterior-distributions))</a></li>
<li class="chapter" data-level="10.3" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#bayes-factors-section-refbayes-factors"><i class="fa fa-check"></i><b>10.3</b> Bayes factors (Section @ref(Bayes-factors))</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html"><i class="fa fa-check"></i><b>11</b> Modeling categorical relationships in R</a><ul>
<li class="chapter" data-level="11.1" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html#the-pearson-chi-squared-test-section-refchi-squared-test"><i class="fa fa-check"></i><b>11.1</b> The Pearson Chi-squared test (Section @ref(chi-squared-test))</a></li>
<li class="chapter" data-level="11.2" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html#two-way-tests-section-reftwo-way-test"><i class="fa fa-check"></i><b>11.2</b> Two-way tests (Section @ref(two-way-test})</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html"><i class="fa fa-check"></i><b>12</b> Modeling continuous relationships in R</a><ul>
<li class="chapter" data-level="12.1" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#computing-covariance-and-correlation-section-refcovariance-and-correlation"><i class="fa fa-check"></i><b>12.1</b> Computing covariance and correlation (Section @ref(covariance-and-correlation))</a></li>
<li class="chapter" data-level="12.2" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#hate-crime-example"><i class="fa fa-check"></i><b>12.2</b> Hate crime example</a></li>
<li class="chapter" data-level="12.3" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#robust-correlations-section-refrobust-correlations"><i class="fa fa-check"></i><b>12.3</b> Robust correlations (Section @ref(robust-correlations))</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html"><i class="fa fa-check"></i><b>13</b> The General Linear Model in R</a><ul>
<li class="chapter" data-level="13.1" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#linear-regression-section-reflinear-regression"><i class="fa fa-check"></i><b>13.1</b> Linear regression (Section @ref(linear-regression))</a></li>
<li class="chapter" data-level="13.2" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#model-criticism-and-diagnostics-section-refmodel-criticism"><i class="fa fa-check"></i><b>13.2</b> Model criticism and diagnostics (Section @ref(model-criticism))</a></li>
<li class="chapter" data-level="13.3" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#examples-of-problematic-model-fit"><i class="fa fa-check"></i><b>13.3</b> Examples of problematic model fit</a></li>
<li class="chapter" data-level="13.4" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#extending-regression-to-binary-outcomes."><i class="fa fa-check"></i><b>13.4</b> Extending regression to binary outcomes.</a></li>
<li class="chapter" data-level="13.5" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#cross-validation-section-refcross-validation"><i class="fa fa-check"></i><b>13.5</b> Cross-validation (Section @ref(cross-validation))</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html"><i class="fa fa-check"></i><b>14</b> Comparing means in R</a><ul>
<li class="chapter" data-level="14.1" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#testing-the-value-of-a-single-mean-section-refsingle-mean"><i class="fa fa-check"></i><b>14.1</b> Testing the value of a single mean (Section @ref(single-mean))</a></li>
<li class="chapter" data-level="14.2" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#comparing-two-means-section-refcomparing-two-means"><i class="fa fa-check"></i><b>14.2</b> Comparing two means (Section @ref(comparing-two-means))</a></li>
<li class="chapter" data-level="14.3" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#the-t-test-as-a-linear-model-section-refttest-linear-model"><i class="fa fa-check"></i><b>14.3</b> The t-test as a linear model (Section @ref(ttest-linear-model))</a></li>
<li class="chapter" data-level="14.4" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#comparing-paired-observations-section-refpaired-ttests"><i class="fa fa-check"></i><b>14.4</b> Comparing paired observations (Section @ref(paired-ttests))</a></li>
<li class="chapter" data-level="14.5" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#analysis-of-variance-section-refanova"><i class="fa fa-check"></i><b>14.5</b> Analysis of variance (Section @ref(ANOVA))</a><ul>
<li class="chapter" data-level="14.5.1" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#repeated-measures-analysis-of-variance"><i class="fa fa-check"></i><b>14.5.1</b> Repeated measures analysis of variance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="practical-statistical-modeling-in-r.html"><a href="practical-statistical-modeling-in-r.html"><i class="fa fa-check"></i><b>15</b> Practical statistical modeling in R</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R companion to Statistical Thinking for the 21st Century</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparing-means-in-r" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> Comparing means in R</h1>
<div id="testing-the-value-of-a-single-mean-section-refsingle-mean" class="section level2">
<h2><span class="header-section-number">14.1</span> Testing the value of a single mean (Section <a href="#single-mean"><strong>??</strong></a>)</h2>
<p>In this example, we will show multiple ways to test a hypothesis about the value of a single mean. As an example, let’s test whether the mean systolic blood pressure (BP) in the NHANES dataset (averaged over the three measurements that were taken for each person) is greater than 120 mm, which is the standard value for normal systolic BP.</p>
<p>First let’s perform a power analysis to see how large our sample would need to be in order to detect a small difference (Cohen’s d = .2).</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" data-line-number="1">pwr.result &lt;-<span class="st"> </span><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="fl">0.2</span>, <span class="dt">power=</span><span class="fl">0.8</span>, </a>
<a class="sourceLine" id="cb266-2" data-line-number="2">           <span class="dt">type=</span><span class="st">&#39;one.sample&#39;</span>, </a>
<a class="sourceLine" id="cb266-3" data-line-number="3">           <span class="dt">alternative=</span><span class="st">&#39;greater&#39;</span>)</a>
<a class="sourceLine" id="cb266-4" data-line-number="4">pwr.result</a></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 155.9256
##               d = 0.2
##       sig.level = 0.05
##           power = 0.8
##     alternative = greater</code></pre>
<p>Based on this, we take a sample of 156 individuals from the dataset.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" data-line-number="1">NHANES_BP_sample &lt;-<span class="st"> </span>NHANES_adult <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-2" data-line-number="2"><span class="st">  </span><span class="kw">drop_na</span>(BPSysAve) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-3" data-line-number="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(BPSysAve) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-4" data-line-number="4"><span class="st">  </span><span class="kw">sample_n</span>(pwr.result<span class="op">$</span>n)</a>
<a class="sourceLine" id="cb268-5" data-line-number="5"></a>
<a class="sourceLine" id="cb268-6" data-line-number="6"><span class="kw">print</span>(<span class="st">&#39;Mean BP:&#39;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Mean BP:&quot;</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1">meanBP &lt;-<span class="st"> </span>NHANES_BP_sample <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-2" data-line-number="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">meanBP=</span><span class="kw">mean</span>(BPSysAve)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-3" data-line-number="3"><span class="st">  </span><span class="kw">pull</span>()</a>
<a class="sourceLine" id="cb270-4" data-line-number="4">meanBP</a></code></pre></div>
<pre><code>## [1] 123.1097</code></pre>
<p>First let’s perform a sign test to see whether the observed mean of 123.11 is significantly different from zero. To do this, we count the number of values that are greater than the hypothesized mean, and then use a binomial test to ask how surprising that number is if the true proportion is 0.5 (as it would be if the distribution were centered at the hypothesized mean).</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1">NHANES_BP_sample &lt;-<span class="st"> </span>NHANES_BP_sample <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb272-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">BPover120=</span>BPSysAve<span class="op">&gt;</span><span class="dv">120</span>)</a>
<a class="sourceLine" id="cb272-3" data-line-number="3"></a>
<a class="sourceLine" id="cb272-4" data-line-number="4">nOver120 &lt;-<span class="st"> </span>NHANES_BP_sample <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb272-5" data-line-number="5"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">nOver120=</span><span class="kw">sum</span>(BPover120)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb272-6" data-line-number="6"><span class="st">  </span><span class="kw">pull</span>()</a>
<a class="sourceLine" id="cb272-7" data-line-number="7"></a>
<a class="sourceLine" id="cb272-8" data-line-number="8"><span class="kw">binom.test</span>(nOver120, <span class="kw">nrow</span>(NHANES_BP_sample), <span class="dt">alternative=</span><span class="st">&#39;greater&#39;</span>)</a></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  nOver120 and nrow(NHANES_BP_sample)
## number of successes = 84, number of trials = 155, p-value = 0.1676
## alternative hypothesis: true probability of success is greater than 0.5
## 95 percent confidence interval:
##  0.4727095 1.0000000
## sample estimates:
## probability of success 
##              0.5419355</code></pre>
<p>This shows no significant difference. Next let’s perform a one-sample t-test:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" data-line-number="1"><span class="kw">t.test</span>(NHANES_BP_sample<span class="op">$</span>BPSysAve, <span class="dt">mu=</span><span class="dv">120</span>, <span class="dt">alternative=</span><span class="st">&#39;greater&#39;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  NHANES_BP_sample$BPSysAve
## t = 2.2045, df = 154, p-value = 0.01449
## alternative hypothesis: true mean is greater than 120
## 95 percent confidence interval:
##  120.7754      Inf
## sample estimates:
## mean of x 
##  123.1097</code></pre>
<p>Here we see that the difference is not statistically signficant. Finally, we can perform a randomization test to test the hypothesis. Under the null hypothesis we would expect roughly half of the differences from the expected mean to be positive and half to be negative (assuming the distribution is centered around the mean), so we can cause the null hypothesis to be true on average by randomly flipping the signs of the differences.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" data-line-number="1">nruns =<span class="st"> </span><span class="dv">5000</span></a>
<a class="sourceLine" id="cb276-2" data-line-number="2"></a>
<a class="sourceLine" id="cb276-3" data-line-number="3"><span class="co"># create a function to compute the </span></a>
<a class="sourceLine" id="cb276-4" data-line-number="4"><span class="co"># t on the shuffled values </span></a>
<a class="sourceLine" id="cb276-5" data-line-number="5">shuffleOneSample &lt;-<span class="st"> </span><span class="cf">function</span>(x,mu) {</a>
<a class="sourceLine" id="cb276-6" data-line-number="6">  <span class="co"># randomly flip signs</span></a>
<a class="sourceLine" id="cb276-7" data-line-number="7">  flip &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="kw">length</span>(x))<span class="op">&gt;</span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb276-8" data-line-number="8">  diff &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span>mu</a>
<a class="sourceLine" id="cb276-9" data-line-number="9">  diff[flip]=<span class="op">-</span><span class="dv">1</span><span class="op">*</span>diff[flip]</a>
<a class="sourceLine" id="cb276-10" data-line-number="10">  <span class="co"># compute and return correlation </span></a>
<a class="sourceLine" id="cb276-11" data-line-number="11">  <span class="co"># with shuffled variable</span></a>
<a class="sourceLine" id="cb276-12" data-line-number="12">  <span class="kw">return</span>(<span class="kw">tibble</span>(<span class="dt">meanDiff=</span><span class="kw">mean</span>(diff)))</a>
<a class="sourceLine" id="cb276-13" data-line-number="13">}</a>
<a class="sourceLine" id="cb276-14" data-line-number="14"></a>
<a class="sourceLine" id="cb276-15" data-line-number="15">index_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">id=</span><span class="kw">seq</span>(nruns)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb276-16" data-line-number="16"><span class="st">  </span><span class="kw">group_by</span>(id)</a>
<a class="sourceLine" id="cb276-17" data-line-number="17"></a>
<a class="sourceLine" id="cb276-18" data-line-number="18">shuffle_results &lt;-<span class="st"> </span>index_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb276-19" data-line-number="19"><span class="st">  </span><span class="kw">do</span>(<span class="kw">shuffleOneSample</span>(NHANES_BP_sample<span class="op">$</span>BPSysAve,<span class="dv">120</span>))</a>
<a class="sourceLine" id="cb276-20" data-line-number="20"></a>
<a class="sourceLine" id="cb276-21" data-line-number="21">observed_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(NHANES_BP_sample<span class="op">$</span>BPSysAve<span class="dv">-120</span>)</a>
<a class="sourceLine" id="cb276-22" data-line-number="22">p_shuffle &lt;-<span class="st"> </span><span class="kw">mean</span>(shuffle_results<span class="op">$</span>meanDiff<span class="op">&gt;</span>observed_diff)</a>
<a class="sourceLine" id="cb276-23" data-line-number="23">p_shuffle</a></code></pre></div>
<pre><code>## [1] 0.014</code></pre>
<p>This gives us a very similar p value to the one observed with the standard t-test.</p>
<p>We might also want to quantify the degree of evidence in favor of the null hypothesis, which we can do using the Bayes Factor:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" data-line-number="1"><span class="kw">ttestBF</span>(NHANES_BP_sample<span class="op">$</span>BPSysAve,</a>
<a class="sourceLine" id="cb278-2" data-line-number="2">        <span class="dt">mu=</span><span class="dv">120</span>,  </a>
<a class="sourceLine" id="cb278-3" data-line-number="3">        <span class="dt">nullInterval =</span> <span class="kw">c</span>(<span class="op">-</span><span class="ot">Inf</span>, <span class="dv">0</span>))</a></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 -Inf&lt;d&lt;0    : 0.02856856 ±0.29%
## [2] Alt., r=0.707 !(-Inf&lt;d&lt;0) : 1.848811   ±0%
## 
## Against denominator:
##   Null, mu = 120 
## ---
## Bayes factor type: BFoneSample, JZS</code></pre>
<p>This tells us that our result doesn’t provide particularly strong evidence for either the null or alternative hypothesis; that is, it’s inconclusive.</p>
</div>
<div id="comparing-two-means-section-refcomparing-two-means" class="section level2">
<h2><span class="header-section-number">14.2</span> Comparing two means (Section <a href="#comparing-two-means"><strong>??</strong></a>)</h2>
<p>To compare two means from independent samples, we can use the two-sample t-test. Let’s say that we want to compare blood pressure of smokers and non-smokers; we don’t have an expectation for the direction, so we will use a two-sided test. First let’s perform a power analysis, again for a small effect:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" data-line-number="1">power_results_2sample &lt;-<span class="st"> </span><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="fl">0.2</span>, <span class="dt">power=</span><span class="fl">0.8</span>,</a>
<a class="sourceLine" id="cb280-2" data-line-number="2">                                    <span class="dt">type=</span><span class="st">&#39;two.sample&#39;</span></a>
<a class="sourceLine" id="cb280-3" data-line-number="3">                                    )</a>
<a class="sourceLine" id="cb280-4" data-line-number="4">power_results_2sample</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 393.4057
##               d = 0.2
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>This tells us that we need 394 subjects in each group, so let’s sample 394 smokers and 394 nonsmokers from the NHANES dataset, and then put them into a single data frame with a variable denoting their smoking status.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" data-line-number="1">nonsmoker_df &lt;-<span class="st"> </span>NHANES_adult <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(SmokeNow<span class="op">==</span><span class="st">&quot;Yes&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-3" data-line-number="3"><span class="st">  </span><span class="kw">drop_na</span>(BPSysAve) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-4" data-line-number="4"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(BPSysAve,SmokeNow) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-5" data-line-number="5"><span class="st">  </span><span class="kw">sample_n</span>(power_results_2sample<span class="op">$</span>n)</a>
<a class="sourceLine" id="cb282-6" data-line-number="6"></a>
<a class="sourceLine" id="cb282-7" data-line-number="7">smoker_df &lt;-<span class="st"> </span>NHANES_adult <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-8" data-line-number="8"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(SmokeNow<span class="op">==</span><span class="st">&quot;No&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-9" data-line-number="9"><span class="st">  </span><span class="kw">drop_na</span>(BPSysAve) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-10" data-line-number="10"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(BPSysAve,SmokeNow) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-11" data-line-number="11"><span class="st">  </span><span class="kw">sample_n</span>(power_results_2sample<span class="op">$</span>n)</a>
<a class="sourceLine" id="cb282-12" data-line-number="12"></a>
<a class="sourceLine" id="cb282-13" data-line-number="13">sample_df &lt;-<span class="st"> </span>smoker_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-14" data-line-number="14"><span class="st">  </span><span class="kw">bind_rows</span>(nonsmoker_df)</a></code></pre></div>
<p>Let’s test our hypothesis using a standard two-sample t-test. We can use the formula notation to specify the analysis, just like we would for <code>lm()</code>.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" data-line-number="1"><span class="kw">t.test</span>(BPSysAve <span class="op">~</span><span class="st"> </span>SmokeNow, <span class="dt">data=</span>sample_df)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BPSysAve by SmokeNow
## t = 4.2105, df = 774.94, p-value = 2.848e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.850860 7.831074
## sample estimates:
##  mean in group No mean in group Yes 
##          125.1603          119.8193</code></pre>
<p>This shows us that there is a significant difference, though the direction is surprising: Smokers have <em>lower</em> blood pressure!</p>
<p>Let’s look at the Bayes factor to quantify the evidence:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb285-1" data-line-number="1">sample_df &lt;-<span class="st"> </span>sample_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb285-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">SmokeNowInt=</span><span class="kw">as.integer</span>(SmokeNow))</a>
<a class="sourceLine" id="cb285-3" data-line-number="3"><span class="kw">ttestBF</span>(<span class="dt">formula=</span>BPSysAve <span class="op">~</span><span class="st"> </span>SmokeNowInt, </a>
<a class="sourceLine" id="cb285-4" data-line-number="4">        <span class="dt">data=</span>sample_df)</a></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 : 440.269 ±0%
## 
## Against denominator:
##   Null, mu1-mu2 = 0 
## ---
## Bayes factor type: BFindepSample, JZS</code></pre>
<p>This shows that there is very strong evidence against the null hypothesis of no difference.</p>
</div>
<div id="the-t-test-as-a-linear-model-section-refttest-linear-model" class="section level2">
<h2><span class="header-section-number">14.3</span> The t-test as a linear model (Section <a href="#ttest-linear-model"><strong>??</strong></a>)</h2>
<p>We can also use <code>lm()</code> to implement these t-tests.</p>
<p>The one-sample t-test is basically a test for whether the intercept is different from zero, so we use a model with only an intercept and apply this to the data after subtracting the null hypothesis mean (so that the expectation under the null hypothesis is an intercept of zero):</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" data-line-number="1">NHANES_BP_sample &lt;-<span class="st"> </span>NHANES_BP_sample <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb287-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">BPSysAveDiff =</span> BPSysAve<span class="dv">-120</span>)</a>
<a class="sourceLine" id="cb287-3" data-line-number="3">lm_result &lt;-<span class="st"> </span><span class="kw">lm</span>(BPSysAveDiff <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>NHANES_BP_sample)</a>
<a class="sourceLine" id="cb287-4" data-line-number="4"><span class="kw">summary</span>(lm_result)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = BPSysAveDiff ~ 1, data = NHANES_BP_sample)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -36.11 -13.11  -1.11   9.39  67.89 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)    3.110      1.411   2.205    0.029 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 17.56 on 154 degrees of freedom</code></pre>
<p>You will notice that this p-value is twice as big as the one obtained from the one-sample t-test above; this is because that was a one-tailed test, while <code>lm()</code> is performing a two-tailed test.</p>
<p>We can also run the two-sample t-test using <code>lm()</code>:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb289-1" data-line-number="1">lm_ttest_result &lt;-<span class="st"> </span><span class="kw">lm</span>(BPSysAve <span class="op">~</span><span class="st"> </span>SmokeNow, <span class="dt">data=</span>sample_df)</a>
<a class="sourceLine" id="cb289-2" data-line-number="2"><span class="kw">summary</span>(lm_ttest_result)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = BPSysAve ~ SmokeNow, data = sample_df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -45.16 -11.16  -2.16   8.84 101.18 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  125.160      0.897  139.54  &lt; 2e-16 ***
## SmokeNowYes   -5.341      1.268   -4.21 2.84e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 17.78 on 784 degrees of freedom
## Multiple R-squared:  0.02211,    Adjusted R-squared:  0.02086 
## F-statistic: 17.73 on 1 and 784 DF,  p-value: 2.844e-05</code></pre>
<p>This gives the same p-value for the SmokeNowYes variable as it did for the two-sample t-test above.</p>
</div>
<div id="comparing-paired-observations-section-refpaired-ttests" class="section level2">
<h2><span class="header-section-number">14.4</span> Comparing paired observations (Section <a href="#paired-ttests"><strong>??</strong></a>)</h2>
<p>Let’s look at how to perform a paired t-test in R. In this case, let’s generate some data for a set of individuals on two tests, where each indivdual varies in their overall ability, but there is also a practice effect such that performance on the second test is generally better than the first.</p>
<p>First, let’s see how big of a sample we will require to find a medium (d=0.5) sized effect. Let’s say that we want to be extra sure in our results, so we will find the sample size that gives us 95% power to find an effect if it’s there:</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb291-1" data-line-number="1">paired_power &lt;-<span class="st"> </span><span class="kw">pwr.t.test</span>(<span class="dt">d=</span><span class="fl">0.5</span>, <span class="dt">power=</span><span class="fl">0.95</span>, <span class="dt">type=</span><span class="st">&#39;paired&#39;</span>, <span class="dt">alternative=</span><span class="st">&#39;greater&#39;</span>)</a>
<a class="sourceLine" id="cb291-2" data-line-number="2">paired_power</a></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 44.67998
##               d = 0.5
##       sig.level = 0.05
##           power = 0.95
##     alternative = greater
## 
## NOTE: n is number of *pairs*</code></pre>
<p>Now let’s generate a dataset with the required number of subjects:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb293-1" data-line-number="1">subject_id &lt;-<span class="st"> </span><span class="kw">seq</span>(paired_power<span class="op">$</span>n)</a>
<a class="sourceLine" id="cb293-2" data-line-number="2"><span class="co"># we code the tests as 0/1 so that we can simply</span></a>
<a class="sourceLine" id="cb293-3" data-line-number="3"><span class="co"># multiply this by the effect to generate the data</span></a>
<a class="sourceLine" id="cb293-4" data-line-number="4">test_id &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb293-5" data-line-number="5">repeat_effect &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb293-6" data-line-number="6">noise_sd &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb293-7" data-line-number="7"></a>
<a class="sourceLine" id="cb293-8" data-line-number="8">subject_means &lt;-<span class="st"> </span><span class="kw">rnorm</span>(paired_power<span class="op">$</span>n, <span class="dt">mean=</span><span class="dv">100</span>, <span class="dt">sd=</span><span class="dv">15</span>)</a>
<a class="sourceLine" id="cb293-9" data-line-number="9">paired_data &lt;-<span class="st"> </span><span class="kw">crossing</span>(subject_id,test_id) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb293-10" data-line-number="10"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">subMean=</span>subject_means[subject_id],</a>
<a class="sourceLine" id="cb293-11" data-line-number="11">         <span class="dt">score=</span>subject_means <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb293-12" data-line-number="12"><span class="st">           </span>test_id<span class="op">*</span>repeat_effect <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb293-13" data-line-number="13"><span class="st">           </span><span class="kw">rnorm</span>(paired_power<span class="op">$</span>n, <span class="dt">mean=</span>noise_sd))</a></code></pre></div>
<p>Let’s perform a paired t-test on these data. To do that, we need to separate the first and second test data into separate variables, which we can do by converting our <em>long</em> data frame into a <em>wide</em> data frame.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" data-line-number="1">paired_data_wide &lt;-<span class="st"> </span>paired_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb294-2" data-line-number="2"><span class="st">  </span><span class="kw">spread</span>(test_id, score) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb294-3" data-line-number="3"><span class="st">  </span><span class="kw">rename</span>(<span class="dt">test1=</span><span class="st">`</span><span class="dt">0</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb294-4" data-line-number="4">         <span class="dt">test2=</span><span class="st">`</span><span class="dt">1</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb294-5" data-line-number="5"></a>
<a class="sourceLine" id="cb294-6" data-line-number="6"><span class="kw">glimpse</span>(paired_data_wide)</a></code></pre></div>
<pre><code>## Observations: 44
## Variables: 4
## $ subject_id &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,…
## $ subMean    &lt;dbl&gt; 116.45972, 94.94520, 103.11749, 91.081…
## $ test1      &lt;dbl&gt; 120.53690, 107.58688, 101.69392, 94.07…
## $ test2      &lt;dbl&gt; 104.44096, 101.07566, 101.86726, 106.6…</code></pre>
<p>Now we can pass those new variables into the <code>t.test()</code> function:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" data-line-number="1">paired_ttest_result &lt;-<span class="st"> </span><span class="kw">t.test</span>(paired_data_wide<span class="op">$</span>test1,</a>
<a class="sourceLine" id="cb296-2" data-line-number="2">                              paired_data_wide<span class="op">$</span>test2,</a>
<a class="sourceLine" id="cb296-3" data-line-number="3">                              <span class="dt">type=</span><span class="st">&#39;paired&#39;</span>)</a>
<a class="sourceLine" id="cb296-4" data-line-number="4">paired_ttest_result </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  paired_data_wide$test1 and paired_data_wide$test2
## t = -1.2799, df = 73.406, p-value = 0.2046
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.536522   2.295414
## sample estimates:
## mean of x mean of y 
##  107.5863  111.7068</code></pre>
<p>This analysis is a bit trickier to perform using the linear model, because we need to estimate a separate intercept for each subject in order to account for the overall differences between subjects. We can’t do this using <code>lm()</code> but we can do it using a function called <code>lmer()</code> from the <code>lme4</code> package. To do this, we need to add <code>(1|subject_id)</code> to the formula, which tells <code>lmer()</code> to add a separate intercept (“1”) for each value of <code>subject_id</code>.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" data-line-number="1">paired_test_lmer &lt;-<span class="st"> </span><span class="kw">lmer</span>(score <span class="op">~</span><span class="st"> </span>test_id <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>subject_id),</a>
<a class="sourceLine" id="cb298-2" data-line-number="2">                         <span class="dt">data=</span>paired_data)</a>
<a class="sourceLine" id="cb298-3" data-line-number="3"><span class="kw">summary</span>(paired_test_lmer)</a></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: score ~ test_id + (1 | subject_id)
##    Data: paired_data
## 
## REML criterion at convergence: 718.6
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.54238 -0.62142 -0.09286  0.73490  2.97925 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev.
##  subject_id (Intercept)   0       0.0    
##  Residual               228      15.1    
## Number of obs: 88, groups:  subject_id, 44
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)  107.586      2.277  86.000   47.26   &lt;2e-16 ***
## test_id        4.121      3.220  86.000    1.28    0.204    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## test_id -0.707
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<p>This gives a similar answer to the standard paired t-test. The advantage is that it’s more flexible, allowing us to perform <em>repeated measures</em> analyses, as we will see below.</p>
</div>
<div id="analysis-of-variance-section-refanova" class="section level2">
<h2><span class="header-section-number">14.5</span> Analysis of variance (Section <a href="#ANOVA"><strong>??</strong></a>)</h2>
<p>Often we want to compare several different means, to determine whether any of them are different from the others. In this case, let’s look at the data from NHANES to determine whether Marital Status is related to sleep quality. First we clean up the data:</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb300-1" data-line-number="1">NHANES_sleep_marriage &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb300-2" data-line-number="2"><span class="st">  </span>NHANES_adult <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb300-3" data-line-number="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(SleepHrsNight, MaritalStatus, Age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb300-4" data-line-number="4"><span class="st">  </span><span class="kw">drop_na</span>()</a></code></pre></div>
<p>In this case we are going to treat the full NHANES dataset as our sample, with the goal of generalizing to the entire US population (from which the NHANES dataset is mean to be a representative sample). First let’s look at the distribution of the different values of the <code>MaritalStatus</code> variable:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb301-1" data-line-number="1">NHANES_sleep_marriage <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb301-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(MaritalStatus) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb301-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n=</span><span class="kw">n</span>()) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb301-4" data-line-number="4"><span class="st">  </span><span class="kw">kable</span>()</a></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
MaritalStatus
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Divorced
</td>
<td style="text-align:right;">
437
</td>
</tr>
<tr>
<td style="text-align:left;">
LivePartner
</td>
<td style="text-align:right;">
370
</td>
</tr>
<tr>
<td style="text-align:left;">
Married
</td>
<td style="text-align:right;">
2434
</td>
</tr>
<tr>
<td style="text-align:left;">
NeverMarried
</td>
<td style="text-align:right;">
889
</td>
</tr>
<tr>
<td style="text-align:left;">
Separated
</td>
<td style="text-align:right;">
134
</td>
</tr>
<tr>
<td style="text-align:left;">
Widowed
</td>
<td style="text-align:right;">
329
</td>
</tr>
</tbody>
</table>
<p>There are reasonable numbers of most of these categories, but let’s remove the <code>Separated</code> category since it has relatively few members:</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb302-1" data-line-number="1">NHANES_sleep_marriage &lt;-</a>
<a class="sourceLine" id="cb302-2" data-line-number="2"><span class="st">  </span>NHANES_sleep_marriage <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb302-3" data-line-number="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">filter</span>(MaritalStatus<span class="op">!=</span><span class="st">&quot;Separated&quot;</span>)</a></code></pre></div>
<p>Now let’s use <code>lm()</code> to perform an analysis of variance. Since we also suspect that Age is related to the amount of sleep, we will also include Age in the model.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb303-1" data-line-number="1">lm_sleep_marriage &lt;-<span class="st"> </span><span class="kw">lm</span>(SleepHrsNight <span class="op">~</span><span class="st"> </span>MaritalStatus <span class="op">+</span><span class="st"> </span>Age,</a>
<a class="sourceLine" id="cb303-2" data-line-number="2">                        <span class="dt">data=</span>NHANES_sleep_marriage)</a>
<a class="sourceLine" id="cb303-3" data-line-number="3"><span class="kw">summary</span>(lm_sleep_marriage)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = SleepHrsNight ~ MaritalStatus + Age, data = NHANES_sleep_marriage)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.0160 -0.8797  0.1065  1.0821  5.2821 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               6.517579   0.098024  66.490  &lt; 2e-16 ***
## MaritalStatusLivePartner  0.143733   0.098692   1.456 0.145360    
## MaritalStatusMarried      0.234936   0.070937   3.312 0.000934 ***
## MaritalStatusNeverMarried 0.251721   0.084036   2.995 0.002756 ** 
## MaritalStatusWidowed      0.263035   0.103270   2.547 0.010896 *  
## Age                       0.003180   0.001415   2.248 0.024643 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.365 on 4453 degrees of freedom
## Multiple R-squared:  0.004583,   Adjusted R-squared:  0.003465 
## F-statistic:   4.1 on 5 and 4453 DF,  p-value: 0.001024</code></pre>
<p>This tells us that there is a highly significant effect of marital status (based on the F test), though it accounts for a very small amount of variance (less than 1%).</p>
<p>It’s also useful to look in more detail at which groups differ from which others, which we can do by examining the <em>estimated marginal means</em> for each group using the <code>emmeans()</code> function.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb305-1" data-line-number="1"><span class="co"># compute the differences between each of the means</span></a>
<a class="sourceLine" id="cb305-2" data-line-number="2">leastsquare &lt;-<span class="st"> </span><span class="kw">emmeans</span>(lm_sleep_marriage, </a>
<a class="sourceLine" id="cb305-3" data-line-number="3">                      pairwise <span class="op">~</span><span class="st"> </span>MaritalStatus,</a>
<a class="sourceLine" id="cb305-4" data-line-number="4">                      <span class="dt">adjust=</span><span class="st">&quot;tukey&quot;</span>)</a>
<a class="sourceLine" id="cb305-5" data-line-number="5"> </a>
<a class="sourceLine" id="cb305-6" data-line-number="6"><span class="co"># display the results by grouping using letters</span></a>
<a class="sourceLine" id="cb305-7" data-line-number="7"></a>
<a class="sourceLine" id="cb305-8" data-line-number="8"><span class="kw">CLD</span>(leastsquare<span class="op">$</span>emmeans, </a>
<a class="sourceLine" id="cb305-9" data-line-number="9">    <span class="dt">alpha=</span>.<span class="dv">05</span>,  </a>
<a class="sourceLine" id="cb305-10" data-line-number="10">    <span class="dt">Letters=</span>letters)</a></code></pre></div>
<pre><code>##  MaritalStatus emmean     SE   df lower.CL upper.CL .group
##  Divorced        6.67 0.0656 4453     6.54     6.80  a    
##  LivePartner     6.81 0.0725 4453     6.67     6.95  ab   
##  Married         6.90 0.0280 4453     6.85     6.96   b   
##  NeverMarried    6.92 0.0501 4453     6.82     7.02   b   
##  Widowed         6.93 0.0823 4453     6.77     7.09  ab   
## 
## Confidence level used: 0.95 
## P value adjustment: tukey method for comparing a family of 5 estimates 
## significance level used: alpha = 0.05</code></pre>
<p>The letters in the <code>group</code> column tell us which individual conditions differ from which others; any pair of conditions that don’t share a group identifier (in this case, the letters <code>a</code> and <code>b</code>) are significantly different from one another. In this case, we see that Divorced people sleep less than Married or Widowed individuals; no other pairs differ significantly.</p>
<div id="repeated-measures-analysis-of-variance" class="section level3">
<h3><span class="header-section-number">14.5.1</span> Repeated measures analysis of variance</h3>
<p>The standard analysis of variance assumes that the observations are independent, which should be true for different people in the NHANES dataset, but may not be true if the data are based on repeated measures of the same individual. For example, the NHANES dataset involves three measurements of blood pressure for each individual. If we want to test whether there are any differences between those, then we would need to use a <em>repeated measures</em> analysis of variance. We can do this using <code>lmer()</code> as we did above. First, we need to create a “long” version of the dataset.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb307-1" data-line-number="1">NHANES_bp_all &lt;-<span class="st"> </span>NHANES_adult <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb307-2" data-line-number="2"><span class="st">  </span><span class="kw">drop_na</span>(BPSys1,BPSys2,BPSys3) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb307-3" data-line-number="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(BPSys1,BPSys2,BPSys3, ID) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb307-4" data-line-number="4"><span class="st">  </span><span class="kw">gather</span>(test, BPsys, <span class="op">-</span>ID)</a></code></pre></div>
<p>Then we fit a model that includes a separate intercept for each individual.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb308-1" data-line-number="1">repeated_lmer &lt;-<span class="kw">lmer</span>(BPsys <span class="op">~</span><span class="st"> </span>test <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>ID), <span class="dt">data=</span>NHANES_bp_all)</a>
<a class="sourceLine" id="cb308-2" data-line-number="2"><span class="kw">summary</span>(repeated_lmer)</a></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: BPsys ~ test + (1 | ID)
##    Data: NHANES_bp_all
## 
## REML criterion at convergence: 89301
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5475 -0.5125 -0.0053  0.4948  4.1339 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  ID       (Intercept) 280.9    16.761  
##  Residual              16.8     4.099  
## Number of obs: 12810, groups:  ID, 4270
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)  122.0037     0.2641 4605.7049  462.04   &lt;2e-16 ***
## testBPSys2    -0.9283     0.0887 8538.0000  -10.47   &lt;2e-16 ***
## testBPSys3    -1.6216     0.0887 8538.0000  -18.28   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) tsBPS2
## testBPSys2 -0.168       
## testBPSys3 -0.168  0.500</code></pre>
<p>This shows us that the second and third tests are significant different from the first test (which was automatically assigned as the baseline by <code>lmer()</code>). We might also want to know whether there is an overall effect of test. We can determine this by comparing the fit of our model to the fit of a model that does not include the test variable, which we will fit here. We then compare the models using the <code>anova()</code> function, which performs an F test to compare the two models.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb310-1" data-line-number="1">repeated_lmer_baseline &lt;-<span class="kw">lmer</span>(BPsys <span class="op">~</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>ID), <span class="dt">data=</span>NHANES_bp_all)</a>
<a class="sourceLine" id="cb310-2" data-line-number="2"><span class="kw">anova</span>(repeated_lmer,repeated_lmer_baseline)</a></code></pre></div>
<pre><code>## Data: NHANES_bp_all
## Models:
## repeated_lmer_baseline: BPsys ~ (1 | ID)
## repeated_lmer: BPsys ~ test + (1 | ID)
##                        Df   AIC   BIC logLik deviance  Chisq Chi Df Pr(&gt;Chisq)
## repeated_lmer_baseline  3 89630 89652 -44812    89624                         
## repeated_lmer           5 89304 89341 -44647    89294 330.15      2  &lt; 2.2e-16
##                           
## repeated_lmer_baseline    
## repeated_lmer          ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This shows that blood pressure differs significantly across the three tests.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-general-linear-model-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="practical-statistical-modeling-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/statsthinking21/statsthinking21-R/edit/master/14-ComparingMeans.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["StatsThinking21.pdf", "StatsThinking21.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
