<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 The General Linear Model in R | Statistical Thinking for the 21st Century</title>
  <meta name="description" content="A book about statistics." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 The General Linear Model in R | Statistical Thinking for the 21st Century" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book about statistics." />
  <meta name="github-repo" content="poldrack/psych10-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 The General Linear Model in R | Statistical Thinking for the 21st Century" />
  
  <meta name="twitter:description" content="A book about statistics." />
  

<meta name="author" content="Copyright 2019 Russell A. Poldrack" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modeling-continuous-relationships-in-r.html"/>
<link rel="next" href="comparing-means-in-r.html"/>
<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129414074-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129414074-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#why-does-this-book-exist"><i class="fa fa-check"></i><b>0.1</b> Why does this book exist?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>0.2</b> Why R?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#the-golden-age-of-data"><i class="fa fa-check"></i><b>0.3</b> The golden age of data</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#an-open-source-book"><i class="fa fa-check"></i><b>0.4</b> An open source book</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.5</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#why-programming-is-hard-to-learn"><i class="fa fa-check"></i><b>1.1</b> Why programming is hard to learn</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#use-the-web"><i class="fa fa-check"></i><b>1.1.1</b> Use the web</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#rubber-duck-debugging"><i class="fa fa-check"></i><b>1.1.2</b> Rubber duck debugging</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#using-rstudio"><i class="fa fa-check"></i><b>1.2</b> Using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-started-with-r"><i class="fa fa-check"></i><b>1.3</b> Getting started with R</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variables"><i class="fa fa-check"></i><b>1.4</b> Variables</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#functions"><i class="fa fa-check"></i><b>1.5</b> Functions</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectors"><i class="fa fa-check"></i><b>1.6</b> Vectors</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#math-with-vectors"><i class="fa fa-check"></i><b>1.7</b> Math with vectors</a></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-frames"><i class="fa fa-check"></i><b>1.8</b> Data Frames</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#using-r-libraries"><i class="fa fa-check"></i><b>1.9</b> Using R libraries</a></li>
<li class="chapter" data-level="1.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#working-with-data-files"><i class="fa fa-check"></i><b>1.10</b> Working with data files</a></li>
<li class="chapter" data-level="1.11" data-path="introduction-to-r.html"><a href="introduction-to-r.html#learning-objectives"><i class="fa fa-check"></i><b>1.11</b> Learning objectives</a></li>
<li class="chapter" data-level="1.12" data-path="introduction-to-r.html"><a href="introduction-to-r.html#suggested-readings-and-videos"><i class="fa fa-check"></i><b>1.12</b> Suggested readings and videos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html"><i class="fa fa-check"></i><b>2</b> Summarizing data with R (with Lucy King)</a><ul>
<li class="chapter" data-level="2.1" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#introduction-to-the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Introduction to the Tidyverse</a><ul>
<li class="chapter" data-level="2.1.1" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#making-a-data-frame-using-tibble"><i class="fa fa-check"></i><b>2.1.1</b> Making a data frame using tibble()</a></li>
<li class="chapter" data-level="2.1.2" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#selecting-an-element"><i class="fa fa-check"></i><b>2.1.2</b> Selecting an element</a></li>
<li class="chapter" data-level="2.1.3" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#adding-a-row-or-column"><i class="fa fa-check"></i><b>2.1.3</b> Adding a row or column</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#creating-or-modifying-variables-using-mutate"><i class="fa fa-check"></i><b>2.2</b> Creating or modifying variables using <code>mutate()</code></a><ul>
<li class="chapter" data-level="2.2.1" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#remove-a-column-using-the-select-function"><i class="fa fa-check"></i><b>2.2.1</b> Remove a column using the select() function</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#tidyverse-in-action"><i class="fa fa-check"></i><b>2.3</b> Tidyverse in action</a></li>
<li class="chapter" data-level="2.4" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#looking-at-individual-variables-using-pull-and-head"><i class="fa fa-check"></i><b>2.4</b> Looking at individual variables using pull() and head()</a></li>
<li class="chapter" data-level="2.5" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#computing-a-frequency-distribution-section-reffrequency-distributions"><i class="fa fa-check"></i><b>2.5</b> Computing a frequency distribution (Section @ref(frequency-distributions))</a></li>
<li class="chapter" data-level="2.6" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#computing-a-cumulative-distribution-section-refcumulative-distributions"><i class="fa fa-check"></i><b>2.6</b> Computing a cumulative distribution (Section @ref(cumulative-distributions))</a></li>
<li class="chapter" data-level="2.7" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#data-cleaning-and-tidying-with-r"><i class="fa fa-check"></i><b>2.7</b> Data cleaning and tidying with R</a><ul>
<li class="chapter" data-level="2.7.1" data-path="summarizing-data-with-r-with-lucy-king.html"><a href="summarizing-data-with-r-with-lucy-king.html#statistics-attitude-data-from-course-survey"><i class="fa fa-check"></i><b>2.7.1</b> Statistics attitude data from course survey</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html"><i class="fa fa-check"></i><b>3</b> Data visualization with R (with Anna Khazenzon)</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#the-grammar-of-graphics"><i class="fa fa-check"></i><b>3.1</b> The grammar of graphics</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#getting-started"><i class="fa fa-check"></i><b>3.2</b> Getting started</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#lets-think-through-a-visualization"><i class="fa fa-check"></i><b>3.3</b> Let’s think through a visualization</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#plotting-the-distribution-of-a-single-variable"><i class="fa fa-check"></i><b>3.4</b> Plotting the distribution of a single variable</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#histogram"><i class="fa fa-check"></i><b>3.4.1</b> Histogram</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#density-plot"><i class="fa fa-check"></i><b>3.4.2</b> Density plot</a></li>
<li class="chapter" data-level="3.4.3" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#bar-vs.line-plots"><i class="fa fa-check"></i><b>3.4.3</b> Bar vs. line plots</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#plots-with-two-variables"><i class="fa fa-check"></i><b>3.5</b> Plots with two variables</a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#adding-on-variables"><i class="fa fa-check"></i><b>3.5.1</b> Adding on variables</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#plotting-dispersion"><i class="fa fa-check"></i><b>3.5.2</b> Plotting dispersion</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#scatter-plot"><i class="fa fa-check"></i><b>3.5.3</b> Scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#creating-a-more-complex-plot"><i class="fa fa-check"></i><b>3.6</b> Creating a more complex plot</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualization-with-r-with-anna-khazenzon.html"><a href="data-visualization-with-r-with-anna-khazenzon.html#additional-reading-and-resources"><i class="fa fa-check"></i><b>3.7</b> Additional reading and resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html"><i class="fa fa-check"></i><b>4</b> Fitting simple models with R</a><ul>
<li class="chapter" data-level="4.1" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html#mean"><i class="fa fa-check"></i><b>4.1</b> Mean</a></li>
<li class="chapter" data-level="4.2" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html#median"><i class="fa fa-check"></i><b>4.2</b> Median</a></li>
<li class="chapter" data-level="4.3" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html#mode"><i class="fa fa-check"></i><b>4.3</b> Mode</a></li>
<li class="chapter" data-level="4.4" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html#variability"><i class="fa fa-check"></i><b>4.4</b> Variability</a></li>
<li class="chapter" data-level="4.5" data-path="fitting-simple-models-with-r.html"><a href="fitting-simple-models-with-r.html#z-scores"><i class="fa fa-check"></i><b>4.5</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html"><i class="fa fa-check"></i><b>5</b> Probability in R (with Lucy King)</a><ul>
<li class="chapter" data-level="5.1" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#basic-probability-calculations"><i class="fa fa-check"></i><b>5.1</b> Basic probability calculations</a></li>
<li class="chapter" data-level="5.2" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#empirical-frequency-section-refempirical-frequency"><i class="fa fa-check"></i><b>5.2</b> Empirical frequency (Section @ref(empirical-frequency))</a></li>
<li class="chapter" data-level="5.3" data-path="probability-in-r-with-lucy-king.html"><a href="probability-in-r-with-lucy-king.html#conditional-probability-section-refconditional-probability"><i class="fa fa-check"></i><b>5.3</b> Conditional probability (Section @ref(conditional-probability))</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-in-r.html"><a href="sampling-in-r.html"><i class="fa fa-check"></i><b>6</b> Sampling in R</a><ul>
<li class="chapter" data-level="6.1" data-path="sampling-in-r.html"><a href="sampling-in-r.html#sampling-error-section-refsamplingerror"><i class="fa fa-check"></i><b>6.1</b> Sampling error (Section @ref(samplingerror))</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-in-r.html"><a href="sampling-in-r.html#central-limit-theorem"><i class="fa fa-check"></i><b>6.2</b> Central limit theorem</a></li>
<li class="chapter" data-level="6.3" data-path="sampling-in-r.html"><a href="sampling-in-r.html#confidence-intervals-section-refconfidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence intervals (Section @ref(confidence-intervals))</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html"><i class="fa fa-check"></i><b>7</b> Resampling and simulation in R</a><ul>
<li class="chapter" data-level="7.1" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#generating-random-samples-section-refgenerating-random-numbers"><i class="fa fa-check"></i><b>7.1</b> Generating random samples (Section @ref(generating-random-numbers))</a></li>
<li class="chapter" data-level="7.2" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#simulating-the-maximum-finishing-time"><i class="fa fa-check"></i><b>7.2</b> Simulating the maximum finishing time</a></li>
<li class="chapter" data-level="7.3" data-path="resampling-and-simulation-in-r.html"><a href="resampling-and-simulation-in-r.html#the-bootstrap"><i class="fa fa-check"></i><b>7.3</b> The bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html"><i class="fa fa-check"></i><b>8</b> Hypothesis testing in R</a><ul>
<li class="chapter" data-level="8.1" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#simple-example-coin-flipping-section-refrandomization-very-simple"><i class="fa fa-check"></i><b>8.1</b> Simple example: Coin-flipping (Section @ref(randomization-very-simple))</a></li>
<li class="chapter" data-level="8.2" data-path="hypothesis-testing-in-r.html"><a href="hypothesis-testing-in-r.html#simulating-p-values"><i class="fa fa-check"></i><b>8.2</b> Simulating p-values</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html"><i class="fa fa-check"></i><b>9</b> Quantifying effects and designing studies</a><ul>
<li class="chapter" data-level="9.1" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#confidence-intervals"><i class="fa fa-check"></i><b>9.1</b> Confidence intervals</a><ul>
<li class="chapter" data-level="9.1.1" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#confidence-intervals-using-the-normal-distribution"><i class="fa fa-check"></i><b>9.1.1</b> Confidence intervals using the normal distribution</a></li>
<li class="chapter" data-level="9.1.2" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#confidence-intervals-using-the-t-distribution"><i class="fa fa-check"></i><b>9.1.2</b> Confidence intervals using the t distribution</a></li>
<li class="chapter" data-level="9.1.3" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#confidence-intervals-and-sample-size"><i class="fa fa-check"></i><b>9.1.3</b> Confidence intervals and sample size</a></li>
<li class="chapter" data-level="9.1.4" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#computing-confidence-intervals-using-the-bootstrap"><i class="fa fa-check"></i><b>9.1.4</b> Computing confidence intervals using the bootstrap</a></li>
<li class="chapter" data-level="9.1.5" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#relation-of-confidence-intervals-to-hypothesis-tests"><i class="fa fa-check"></i><b>9.1.5</b> Relation of confidence intervals to hypothesis tests</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#effect-sizes"><i class="fa fa-check"></i><b>9.2</b> Effect sizes</a><ul>
<li class="chapter" data-level="9.2.1" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#cohens-d"><i class="fa fa-check"></i><b>9.2.1</b> Cohen’s D</a></li>
<li class="chapter" data-level="9.2.2" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#pearsons-r"><i class="fa fa-check"></i><b>9.2.2</b> Pearson’s r</a></li>
<li class="chapter" data-level="9.2.3" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#odds-ratio"><i class="fa fa-check"></i><b>9.2.3</b> Odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#statistical-power"><i class="fa fa-check"></i><b>9.3</b> Statistical power</a><ul>
<li class="chapter" data-level="9.3.1" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#power-analysis"><i class="fa fa-check"></i><b>9.3.1</b> Power analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#learning-objectives-1"><i class="fa fa-check"></i><b>9.4</b> Learning objectives</a></li>
<li class="chapter" data-level="9.5" data-path="ci-effect-size-power.html"><a href="ci-effect-size-power.html#suggested-readings"><i class="fa fa-check"></i><b>9.5</b> Suggested readings</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html"><i class="fa fa-check"></i><b>10</b> Statistical power in R</a><ul>
<li class="chapter" data-level="10.1" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#power-analysis-1"><i class="fa fa-check"></i><b>10.1</b> Power analysis</a></li>
<li class="chapter" data-level="10.2" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#power-curves"><i class="fa fa-check"></i><b>10.2</b> Power curves</a></li>
<li class="chapter" data-level="10.3" data-path="statistical-power-in-r.html"><a href="statistical-power-in-r.html#simulating-statistical-power"><i class="fa fa-check"></i><b>10.3</b> Simulating statistical power</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html"><i class="fa fa-check"></i><b>11</b> Bayesian statistics in R</a><ul>
<li class="chapter" data-level="11.1" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#a-simple-example-section-refdoing-bayesian-estimation"><i class="fa fa-check"></i><b>11.1</b> A simple example (Section @ref(doing-bayesian-estimation))</a></li>
<li class="chapter" data-level="11.2" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#estimating-posterior-distributions-section-refestimating-posterior-distributions"><i class="fa fa-check"></i><b>11.2</b> Estimating posterior distributions (Section @ref(estimating-posterior-distributions))</a></li>
<li class="chapter" data-level="11.3" data-path="bayesian-statistics-in-r.html"><a href="bayesian-statistics-in-r.html#bayes-factors-section-refbayes-factors"><i class="fa fa-check"></i><b>11.3</b> Bayes factors (Section @ref(Bayes-factors))</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html"><i class="fa fa-check"></i><b>12</b> Modeling categorical relationships in R</a><ul>
<li class="chapter" data-level="12.1" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html#the-pearson-chi-squared-test-section-refchi-squared-test"><i class="fa fa-check"></i><b>12.1</b> The Pearson Chi-squared test (Section @ref(chi-squared-test))</a></li>
<li class="chapter" data-level="12.2" data-path="modeling-categorical-relationships-in-r.html"><a href="modeling-categorical-relationships-in-r.html#two-way-tests-section-reftwo-way-test"><i class="fa fa-check"></i><b>12.2</b> Two-way tests (Section @ref(two-way-test})</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html"><i class="fa fa-check"></i><b>13</b> Modeling continuous relationships in R</a><ul>
<li class="chapter" data-level="13.1" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#computing-covariance-and-correlation-section-refcovariance-and-correlation"><i class="fa fa-check"></i><b>13.1</b> Computing covariance and correlation (Section @ref(covariance-and-correlation))</a></li>
<li class="chapter" data-level="13.2" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#hate-crime-example"><i class="fa fa-check"></i><b>13.2</b> Hate crime example</a></li>
<li class="chapter" data-level="13.3" data-path="modeling-continuous-relationships-in-r.html"><a href="modeling-continuous-relationships-in-r.html#robust-correlations-section-refrobust-correlations"><i class="fa fa-check"></i><b>13.3</b> Robust correlations (Section @ref(robust-correlations))</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html"><i class="fa fa-check"></i><b>14</b> The General Linear Model in R</a><ul>
<li class="chapter" data-level="14.1" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#linear-regression-section-reflinear-regression"><i class="fa fa-check"></i><b>14.1</b> Linear regression (Section @ref(linear-regression))</a></li>
<li class="chapter" data-level="14.2" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#model-criticism-and-diagnostics-section-refmodel-criticism"><i class="fa fa-check"></i><b>14.2</b> Model criticism and diagnostics (Section @ref(model-criticism))</a></li>
<li class="chapter" data-level="14.3" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#examples-of-problematic-model-fit"><i class="fa fa-check"></i><b>14.3</b> Examples of problematic model fit</a></li>
<li class="chapter" data-level="14.4" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#extending-regression-to-binary-outcomes."><i class="fa fa-check"></i><b>14.4</b> Extending regression to binary outcomes.</a></li>
<li class="chapter" data-level="14.5" data-path="the-general-linear-model-in-r.html"><a href="the-general-linear-model-in-r.html#cross-validation-section-refcross-validation"><i class="fa fa-check"></i><b>14.5</b> Cross-validation (Section @ref(cross-validation))</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html"><i class="fa fa-check"></i><b>15</b> Comparing means in R</a><ul>
<li class="chapter" data-level="15.1" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#testing-the-value-of-a-single-mean-section-refsingle-mean"><i class="fa fa-check"></i><b>15.1</b> Testing the value of a single mean (Section @ref(single-mean))</a></li>
<li class="chapter" data-level="15.2" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#comparing-two-means-section-refcomparing-two-means"><i class="fa fa-check"></i><b>15.2</b> Comparing two means (Section @ref(comparing-two-means))</a></li>
<li class="chapter" data-level="15.3" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#the-t-test-as-a-linear-model-section-refttest-linear-model"><i class="fa fa-check"></i><b>15.3</b> The t-test as a linear model (Section @ref(ttest-linear-model))</a></li>
<li class="chapter" data-level="15.4" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#comparing-paired-observations-section-refpaired-ttests"><i class="fa fa-check"></i><b>15.4</b> Comparing paired observations (Section @ref(paired-ttests))</a></li>
<li class="chapter" data-level="15.5" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#analysis-of-variance-section-refanova"><i class="fa fa-check"></i><b>15.5</b> Analysis of variance (Section @ref(ANOVA))</a><ul>
<li class="chapter" data-level="15.5.1" data-path="comparing-means-in-r.html"><a href="comparing-means-in-r.html#repeated-measures-analysis-of-variance"><i class="fa fa-check"></i><b>15.5.1</b> Repeated measures analysis of variance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="practical-statistical-modeling-in-r.html"><a href="practical-statistical-modeling-in-r.html"><i class="fa fa-check"></i><b>16</b> Practical statistical modeling in R</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Thinking for the 21st Century</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-general-linear-model-in-r" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> The General Linear Model in R</h1>
<div id="linear-regression-section-reflinear-regression" class="section level2">
<h2><span class="header-section-number">14.1</span> Linear regression (Section <a href="#linear-regression"><strong>??</strong></a>)</h2>
<p>To perform linear regression in R, we use the <code>lm()</code> function. Let’s generate some data and use this function to compute the linear regression solution.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" data-line-number="1">npoints &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb247-2" data-line-number="2">intercept =<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb247-3" data-line-number="3"><span class="co"># slope of X/Y relationship</span></a>
<a class="sourceLine" id="cb247-4" data-line-number="4">slope=<span class="fl">0.5</span></a>
<a class="sourceLine" id="cb247-5" data-line-number="5"><span class="co"># this lets us control the strength of the relationship</span></a>
<a class="sourceLine" id="cb247-6" data-line-number="6"><span class="co"># by varying the amount of noise added to the y variable</span></a>
<a class="sourceLine" id="cb247-7" data-line-number="7">noise_sd =<span class="st"> </span><span class="fl">0.6</span></a>
<a class="sourceLine" id="cb247-8" data-line-number="8"></a>
<a class="sourceLine" id="cb247-9" data-line-number="9">regression_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">x =</span> <span class="kw">rnorm</span>(npoints)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-10" data-line-number="10"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">y =</span> x<span class="op">*</span>slope <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(npoints)<span class="op">*</span>noise_sd <span class="op">+</span><span class="st"> </span>intercept)</a>
<a class="sourceLine" id="cb247-11" data-line-number="11"></a>
<a class="sourceLine" id="cb247-12" data-line-number="12"><span class="kw">ggplot</span>(regression_data,<span class="kw">aes</span>(x,y)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb247-13" data-line-number="13"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="StatsThinking21_files/figure-html/unnamed-chunk-159-1.png" width="50%" /></p>
<p>We can then apply <code>lm()</code> to these data:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">lm_result &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x, <span class="dt">data=</span>regression_data)</a>
<a class="sourceLine" id="cb248-2" data-line-number="2"><span class="kw">summary</span>(lm_result)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = regression_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.55632 -0.30424 -0.00587  0.38039  1.25219 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  9.97610    0.05796 172.122  &lt; 2e-16 ***
## x            0.37246    0.05862   6.353 6.65e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5795 on 98 degrees of freedom
## Multiple R-squared:  0.2917, Adjusted R-squared:  0.2845 
## F-statistic: 40.36 on 1 and 98 DF,  p-value: 6.646e-09</code></pre>
<p>We should see three things in the <code>lm()</code> results:</p>
<ul>
<li>The estimate of the Intercept in the model should be very close to the intercept that we specified</li>
<li>The estimate for the x parameter should be very close to the slope that we specified</li>
<li>The residual standard error should be roughly similar to the noise standard deviation that we specified</li>
</ul>
</div>
<div id="model-criticism-and-diagnostics-section-refmodel-criticism" class="section level2">
<h2><span class="header-section-number">14.2</span> Model criticism and diagnostics (Section <a href="#model-criticism"><strong>??</strong></a>)</h2>
<p>Once we have fitted the model, we want to look at some diagnostics to determine whether the model is actually fitting properly. We can do this using the <code>autoplot()</code> function from the <code>ggfortify</code> package.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" data-line-number="1"><span class="kw">autoplot</span>(lm_result,<span class="dt">which=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="StatsThinking21_files/figure-html/unnamed-chunk-161-1.png" width="80%" /></p>
<p>The left panel in this plot shows the relationship between the predicted (or “fitted”) values and the residuals. We would like to make sure that there is no clear relationship between these two (as we will see below). The right panel shows a Q-Q plot, which helps us assess whether the residuals from the model are normally distributed. In this case, they look reasonably normal, as the points don’t differ too much from the unit line.</p>
</div>
<div id="examples-of-problematic-model-fit" class="section level2">
<h2><span class="header-section-number">14.3</span> Examples of problematic model fit</h2>
<p>Let’s say that there was another variable at play in this dataset, which we were not aware of. This variable causes some of the cases to have much larger values than others, in a way that is unrelated to the X variable. We play a trick here using the <code>seq()</code> function to create a sequence from zero to one, and then threshold those 0.5 (in order to obtain half of the values as zero and the other half as one) and then multiply by the desired effect size:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1">effsize=<span class="dv">2</span></a>
<a class="sourceLine" id="cb251-2" data-line-number="2">regression_data &lt;-<span class="st"> </span>regression_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb251-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">y2=</span>y <span class="op">+</span><span class="st"> </span>effsize<span class="op">*</span>(<span class="kw">seq</span>(<span class="dv">1</span><span class="op">/</span>npoints,<span class="dv">1</span>,<span class="dv">1</span><span class="op">/</span>npoints)<span class="op">&gt;</span><span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb251-4" data-line-number="4"></a>
<a class="sourceLine" id="cb251-5" data-line-number="5">lm_result2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y2 <span class="op">~</span><span class="st"> </span>x, <span class="dt">data=</span>regression_data)</a>
<a class="sourceLine" id="cb251-6" data-line-number="6"><span class="kw">summary</span>(lm_result2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y2 ~ x, data = regression_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.33243 -0.96887 -0.09385  1.04213  2.25913 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  10.9778     0.1172  93.646   &lt;2e-16 ***
## x             0.2696     0.1186   2.273   0.0252 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.172 on 98 degrees of freedom
## Multiple R-squared:  0.0501, Adjusted R-squared:  0.04041 
## F-statistic: 5.169 on 1 and 98 DF,  p-value: 0.02518</code></pre>
<p>One thing you should notice is that the model now fits overall much worse; the R-squared is about half of what it was in the previous model, which reflects the fact that more variability was added to the data, but it wasn’t accounted for in the model. Let’s see if our diagnostic reports can give us any insight:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" data-line-number="1"><span class="kw">autoplot</span>(lm_result2,<span class="dt">which=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="StatsThinking21_files/figure-html/unnamed-chunk-163-1.png" width="80%" /></p>
<p>The residual versus fitted graph doesn’t give us much insight, but we see from the Q-Q plot that the residuals are diverging quite a bit from the unit line.</p>
<p>Let’s look at another potential problem, in which the y variable is nonlinearly related to the X variable. We can create these data by squaring the X variable when we generate the Y variable:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" data-line-number="1">effsize=<span class="dv">2</span></a>
<a class="sourceLine" id="cb254-2" data-line-number="2">regression_data &lt;-<span class="st"> </span>regression_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb254-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">y3 =</span> (x<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>slope <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(npoints)<span class="op">*</span>noise_sd <span class="op">+</span><span class="st"> </span>intercept)</a>
<a class="sourceLine" id="cb254-4" data-line-number="4"></a>
<a class="sourceLine" id="cb254-5" data-line-number="5">lm_result3 &lt;-<span class="st"> </span><span class="kw">lm</span>(y3 <span class="op">~</span><span class="st"> </span>x, <span class="dt">data=</span>regression_data)</a>
<a class="sourceLine" id="cb254-6" data-line-number="6"><span class="kw">summary</span>(lm_result3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y3 ~ x, data = regression_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6100 -0.5679 -0.0649  0.3587  3.2662 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 10.55467    0.08439 125.073   &lt;2e-16 ***
## x           -0.04189    0.08536  -0.491    0.625    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8438 on 98 degrees of freedom
## Multiple R-squared:  0.002452,   Adjusted R-squared:  -0.007727 
## F-statistic: 0.2409 on 1 and 98 DF,  p-value: 0.6247</code></pre>
<p>Now we see that there is no significant linear relationship between <span class="math inline">\(X^2\)</span> and Y/ But if we look at the residuals the problem with the model becomes clear:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" data-line-number="1"><span class="kw">autoplot</span>(lm_result3,<span class="dt">which=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="StatsThinking21_files/figure-html/unnamed-chunk-165-1.png" width="80%" /></p>
<p>In this case we can see the clearly nonlinear relationship between the predicted and residual values, as well as the clear lack of normality in the residuals.</p>
<p>As we noted in the previous chapter, the “linear” in the general linear model doesn’t refer to the shape of the response, but instead refers to the fact that model is linear in its parameters — that is, the predictors in the model only get multiplied the parameters (e.g., rather than being raised to a power of the parameter). Here is how we would build a model that could account for the nonlinear relationship:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" data-line-number="1"><span class="co"># create x^2 variable</span></a>
<a class="sourceLine" id="cb257-2" data-line-number="2">regression_data &lt;-<span class="st"> </span>regression_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">x_squared =</span> x<span class="op">**</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb257-4" data-line-number="4"></a>
<a class="sourceLine" id="cb257-5" data-line-number="5">lm_result4 &lt;-<span class="st"> </span><span class="kw">lm</span>(y3 <span class="op">~</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span>x_squared, <span class="dt">data=</span>regression_data)</a>
<a class="sourceLine" id="cb257-6" data-line-number="6"><span class="kw">summary</span>(lm_result4)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y3 ~ x + x_squared, data = regression_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.41009 -0.37915 -0.00483  0.39079  1.44368 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 10.10875    0.07387 136.836   &lt;2e-16 ***
## x           -0.01178    0.05998  -0.196    0.845    
## x_squared    0.45569    0.04513  10.098   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5922 on 97 degrees of freedom
## Multiple R-squared:  0.5137, Adjusted R-squared:  0.5037 
## F-statistic: 51.23 on 2 and 97 DF,  p-value: 6.536e-16</code></pre>
<p>Now we see that the effect of <span class="math inline">\(X^2\)</span> is significant, and if we look at the residual plot we should see that things look much better:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" data-line-number="1"><span class="kw">autoplot</span>(lm_result4,<span class="dt">which=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="StatsThinking21_files/figure-html/unnamed-chunk-167-1.png" width="80%" />
Not perfect, but much better than before!</p>
</div>
<div id="extending-regression-to-binary-outcomes." class="section level2">
<h2><span class="header-section-number">14.4</span> Extending regression to binary outcomes.</h2>
<p>Let’s say that we have a blood test (which is often referred to as a <em>biomarker</em>) and we want to know whether it predicts who is going to have a heart attack within the next year. We will generate a synthetic dataset for a population that is at very high risk for a heart attack in the next year.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" data-line-number="1"><span class="co"># sample size</span></a>
<a class="sourceLine" id="cb260-2" data-line-number="2">npatients=<span class="dv">1000</span></a>
<a class="sourceLine" id="cb260-3" data-line-number="3"></a>
<a class="sourceLine" id="cb260-4" data-line-number="4"><span class="co"># probability of heart attack</span></a>
<a class="sourceLine" id="cb260-5" data-line-number="5">p_heartattack =<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb260-6" data-line-number="6"></a>
<a class="sourceLine" id="cb260-7" data-line-number="7"><span class="co"># true relation to biomarker</span></a>
<a class="sourceLine" id="cb260-8" data-line-number="8">true_effect &lt;-<span class="st"> </span><span class="fl">0.6</span></a>
<a class="sourceLine" id="cb260-9" data-line-number="9"></a>
<a class="sourceLine" id="cb260-10" data-line-number="10"><span class="co"># assume biomarker is normally distributed</span></a>
<a class="sourceLine" id="cb260-11" data-line-number="11">disease_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">biomarker=</span><span class="kw">rnorm</span>(npatients))</a>
<a class="sourceLine" id="cb260-12" data-line-number="12"></a>
<a class="sourceLine" id="cb260-13" data-line-number="13"><span class="co"># generate another variable that reflects risk for </span></a>
<a class="sourceLine" id="cb260-14" data-line-number="14"><span class="co"># heart attack, which is related to the biomarker</span></a>
<a class="sourceLine" id="cb260-15" data-line-number="15">disease_df &lt;-<span class="st"> </span>disease_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb260-16" data-line-number="16"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">risk =</span> biomarker<span class="op">*</span>true_effect <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(npatients))</a>
<a class="sourceLine" id="cb260-17" data-line-number="17"></a>
<a class="sourceLine" id="cb260-18" data-line-number="18"><span class="co"># create another variable that shows who has a </span></a>
<a class="sourceLine" id="cb260-19" data-line-number="19"><span class="co"># heart attack, based on the risk variable</span></a>
<a class="sourceLine" id="cb260-20" data-line-number="20">disease_df &lt;-<span class="st"> </span>disease_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb260-21" data-line-number="21"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb260-22" data-line-number="22">    <span class="dt">heartattack =</span> risk <span class="op">&gt;</span><span class="st"> </span><span class="kw">quantile</span>(disease_df<span class="op">$</span>risk,</a>
<a class="sourceLine" id="cb260-23" data-line-number="23">                                       <span class="dv">1</span><span class="op">-</span>p_heartattack))</a>
<a class="sourceLine" id="cb260-24" data-line-number="24"></a>
<a class="sourceLine" id="cb260-25" data-line-number="25"><span class="kw">glimpse</span>(disease_df)</a></code></pre></div>
<pre><code>## Observations: 1,000
## Variables: 3
## $ biomarker   &lt;dbl&gt; 1.1512317, 0.6753651, 1.2141696, -0.7…
## $ risk        &lt;dbl&gt; 1.05356169, -0.52889832, 0.67528209, …
## $ heartattack &lt;lgl&gt; TRUE, FALSE, TRUE, FALSE, FALSE, TRUE…</code></pre>
<p>Now we would like to build a model that allows us to predict who will have a heart attack from these data. However, you may have noticed that the heartattack variable is a binary variable; because linear regression assumes that the residuals from the model will be normally distributed, and the binary nature of the data will violate this, we instead need to use a different kind of model, known as a <em>logistic regression</em> model, which is built to deal with binary outcomes. We can fit this model using the <code>glm()</code> function:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" data-line-number="1">glm_result &lt;-<span class="st"> </span><span class="kw">glm</span>(heartattack <span class="op">~</span><span class="st"> </span>biomarker, <span class="dt">data=</span>disease_df,</a>
<a class="sourceLine" id="cb262-2" data-line-number="2">                  <span class="dt">family=</span><span class="kw">binomial</span>())</a>
<a class="sourceLine" id="cb262-3" data-line-number="3"><span class="kw">summary</span>(glm_result)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = heartattack ~ biomarker, family = binomial(), data = disease_df)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.13007  -1.01501   0.03054   1.00492   2.13191  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.004117   0.069479  -0.059    0.953    
## biomarker    0.996366   0.083418  11.944   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1386.3  on 999  degrees of freedom
## Residual deviance: 1201.4  on 998  degrees of freedom
## AIC: 1205.4
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<p>This looks very similar to the output from the <code>lm()</code> function, and it shows us that there is a significant relationship between the biomarker and heart attacks. The model provides us with a predicted probability that each individual will have a heart attack; if this is greater than 0.5, then that means that the model predicts that the individual is more likely than not to have a heart attack.<br />
We can start by simply comparing those predictions to the actual outcomes.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" data-line-number="1"><span class="co"># add predictions to data frame</span></a>
<a class="sourceLine" id="cb264-2" data-line-number="2">disease_df &lt;-<span class="st"> </span>disease_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb264-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prediction =</span> glm_result<span class="op">$</span>fitted.values<span class="op">&gt;</span><span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb264-4" data-line-number="4">         <span class="dt">heartattack =</span> heartattack)</a>
<a class="sourceLine" id="cb264-5" data-line-number="5"></a>
<a class="sourceLine" id="cb264-6" data-line-number="6"><span class="co"># create table comparing predicted to actual outcomes</span></a>
<a class="sourceLine" id="cb264-7" data-line-number="7"><span class="kw">CrossTable</span>(disease_df<span class="op">$</span>prediction,</a>
<a class="sourceLine" id="cb264-8" data-line-number="8">           disease_df<span class="op">$</span>heartattack,</a>
<a class="sourceLine" id="cb264-9" data-line-number="9">           <span class="dt">prop.t=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb264-10" data-line-number="10">           <span class="dt">prop.r=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb264-11" data-line-number="11">           <span class="dt">prop.chisq=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Col Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1000 
## 
##  
##                       | disease_df$heartattack 
## disease_df$prediction |     FALSE |      TRUE | Row Total | 
## ----------------------|-----------|-----------|-----------|
##                 FALSE |       332 |       157 |       489 | 
##                       |     0.664 |     0.314 |           | 
## ----------------------|-----------|-----------|-----------|
##                  TRUE |       168 |       343 |       511 | 
##                       |     0.336 |     0.686 |           | 
## ----------------------|-----------|-----------|-----------|
##          Column Total |       500 |       500 |      1000 | 
##                       |     0.500 |     0.500 |           | 
## ----------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>This shows us that of the 500 people who had heart attacks, the model corrected predicted a heart attack for 343 of them. It also predicted heart attacks for 168 people who didn’t have them, and it failed to predict a heart attack for 157 people who had them. This highlights the distinction that we mentioned before between statistical and practical significance; even though the biomarker shows a highly significant relationship to heart attacks, it’s ability to predict them is still relatively poor. As we will see below, it gets even worse when we try to generalize this to a new group of people.</p>
</div>
<div id="cross-validation-section-refcross-validation" class="section level2">
<h2><span class="header-section-number">14.5</span> Cross-validation (Section <a href="#cross-validation"><strong>??</strong></a>)</h2>
<p>Cross-validation is a powerful technique that allows us to estimate how well our results will generalize to a new dataset. Here we will build our own crossvalidation code to see how it works, continuing the logistic regression example from the previous section.</p>
<p>In cross-validation, we want to split the data into several subsets and then iteratively train the model while leaving out each subset (which we usually call <em>folds</em>) and then test the model on that held-out fold Let’s write our own code to do this splitting; one relatively easy way to this is to create a vector that contains the fold numbers, and then randomly shuffle it to create the fold assigments for each data point.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" data-line-number="1">nfolds &lt;-<span class="st"> </span><span class="dv">4</span> <span class="co"># number of folds</span></a>
<a class="sourceLine" id="cb266-2" data-line-number="2"></a>
<a class="sourceLine" id="cb266-3" data-line-number="3"><span class="co"># we use the kronecker() function to repeat the folds</span></a>
<a class="sourceLine" id="cb266-4" data-line-number="4">fold &lt;-<span class="st">  </span><span class="kw">kronecker</span>(<span class="kw">seq</span>(nfolds),<span class="kw">rep</span>(<span class="dv">1</span>,npatients<span class="op">/</span>nfolds))</a>
<a class="sourceLine" id="cb266-5" data-line-number="5"><span class="co"># randomly shuffle using the sample() function</span></a>
<a class="sourceLine" id="cb266-6" data-line-number="6">fold &lt;-<span class="st"> </span><span class="kw">sample</span>(fold)</a>
<a class="sourceLine" id="cb266-7" data-line-number="7"></a>
<a class="sourceLine" id="cb266-8" data-line-number="8"><span class="co"># add variable to store CV predictions</span></a>
<a class="sourceLine" id="cb266-9" data-line-number="9">disease_df &lt;-<span class="st"> </span>disease_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-10" data-line-number="10"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">CVpred=</span><span class="ot">NA</span>)</a>
<a class="sourceLine" id="cb266-11" data-line-number="11"></a>
<a class="sourceLine" id="cb266-12" data-line-number="12"><span class="co"># now loop through folds and separate training and test data</span></a>
<a class="sourceLine" id="cb266-13" data-line-number="13"><span class="cf">for</span> (f <span class="cf">in</span> <span class="kw">seq</span>(nfolds)){</a>
<a class="sourceLine" id="cb266-14" data-line-number="14">  <span class="co"># get training and test data</span></a>
<a class="sourceLine" id="cb266-15" data-line-number="15">  train_df &lt;-<span class="st"> </span>disease_df[fold<span class="op">!=</span>f,]</a>
<a class="sourceLine" id="cb266-16" data-line-number="16">  test_df &lt;-<span class="st"> </span>disease_df[fold<span class="op">==</span>f,]</a>
<a class="sourceLine" id="cb266-17" data-line-number="17">  <span class="co"># fit model to training data</span></a>
<a class="sourceLine" id="cb266-18" data-line-number="18">  glm_result_cv &lt;-<span class="st"> </span><span class="kw">glm</span>(heartattack <span class="op">~</span><span class="st"> </span>biomarker, <span class="dt">data=</span>train_df,</a>
<a class="sourceLine" id="cb266-19" data-line-number="19">                  <span class="dt">family=</span><span class="kw">binomial</span>())</a>
<a class="sourceLine" id="cb266-20" data-line-number="20">  <span class="co"># get probability of heart attack on test data</span></a>
<a class="sourceLine" id="cb266-21" data-line-number="21">  pred &lt;-<span class="st"> </span><span class="kw">predict</span>(glm_result_cv,<span class="dt">newdata =</span> test_df)</a>
<a class="sourceLine" id="cb266-22" data-line-number="22">  <span class="co"># convert to prediction and put into data frame</span></a>
<a class="sourceLine" id="cb266-23" data-line-number="23">  disease_df<span class="op">$</span>CVpred[fold<span class="op">==</span>f] =<span class="st"> </span>(pred<span class="op">&gt;</span><span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb266-24" data-line-number="24"></a>
<a class="sourceLine" id="cb266-25" data-line-number="25">}</a></code></pre></div>
<p>Now let’s look at the performance of the model:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" data-line-number="1"><span class="co"># create table comparing predicted to actual outcomes</span></a>
<a class="sourceLine" id="cb267-2" data-line-number="2"><span class="kw">CrossTable</span>(disease_df<span class="op">$</span>CVpred,</a>
<a class="sourceLine" id="cb267-3" data-line-number="3">           disease_df<span class="op">$</span>heartattack,</a>
<a class="sourceLine" id="cb267-4" data-line-number="4">           <span class="dt">prop.t=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb267-5" data-line-number="5">           <span class="dt">prop.r=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb267-6" data-line-number="6">           <span class="dt">prop.chisq=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Col Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1000 
## 
##  
##                   | disease_df$heartattack 
## disease_df$CVpred |     FALSE |      TRUE | Row Total | 
## ------------------|-----------|-----------|-----------|
##             FALSE |       416 |       269 |       685 | 
##                   |     0.832 |     0.538 |           | 
## ------------------|-----------|-----------|-----------|
##              TRUE |        84 |       231 |       315 | 
##                   |     0.168 |     0.462 |           | 
## ------------------|-----------|-----------|-----------|
##      Column Total |       500 |       500 |      1000 | 
##                   |     0.500 |     0.500 |           | 
## ------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>Now we see that the model only accurately predicts less than half of the heart attacks that occurred when it is predicting to a new sample. This tells us that this is the level of prediction that we could expect if were to apply the model to a new sample of patients from the same population.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modeling-continuous-relationships-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comparing-means-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/poldrack/psych10-book/edit/master/14b-GeneralLinearModelInR.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["StatsThinking21.pdf", "StatsThinking21.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
